version: '3'
volumes:
  database_data:
    driver: local
  static_content:
    driver: local
  #cache:
  #  driver_opts:
  #    type: tmpfs
  #    device: tmpfs
networks:
  default:
    driver: bridge
  external:
    external:
      name: rnet 
services:
  resto:
    image: jjrom/resto:6.0
    restart: always
    build:
      context: ./
      dockerfile: ./build/resto/Dockerfile
    depends_on:
      - restodb
    networks:
      - default
      - external
    ports:
      - ${RESTO_EXPOSED_PORT:-5252}:80
    env_file:
      - ${ENV_FILE:-config.env}
    environment: 
      # Set to 0 in production environment to activate opcache
      - RESTO_DEBUG=1
      - PHP_ENABLE_XDEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m
      timeout: 5s
    volumes:
      - ${RESTO_STATIC_CONTENT:-static_content}:/var/www/static
      - ./app:/app
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/src/STAC.php:/app/resto/addons/STAC.php
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/stac.config:/cfg/stac.config
  restodb:
    image: jjrom/resto-database:6.0
    restart: always
    build:
      context: ./
      dockerfile: ./build/resto-database/Dockerfile
    command: docker-entrypoint.sh -c config_file=/etc/postgresql.conf
    networks:
      - default
      - external
    env_file:
      - ${ENV_FILE:-config.env}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD:-resto}
      - POSTGRES_USER=${DATABASE_USER_NAME:-resto}
      - POSTGRES_DB=${DATABASE_NAME:-resto}
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_SHARED_BUFFERS=1GB
      - POSTGRES_WORK_MEM=32MB
      - POSTGRES_MAINTENANCE_WORK_MEM=320MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=3GB
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    ports:
      - ${DATABASE_EXPOSED_PORT:-5253}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER_NAME:-resto}"]
      interval: 1m
      timeout: 5s
    volumes:
      - ${POSTGRES_DATA:-database_data}:/var/lib/postgresql/data
