version: '3.5'
services:
  resto:
    environment: 
      # Set to 0 in production environment to activate opcache
      - RESTO_DEBUG=1
      - PHP_ENABLE_XDEBUG=1
    volumes:
      - ./app/resto:/app/resto:ro
      - ./app/vendor:/app/vendor:ro