version: '3'
services:
  resto:
    environment: 
      # Set to 0 in production environment to activate opcache
      - RESTO_DEBUG=1
      - PHP_ENABLE_XDEBUG=1
    volumes:
      - ./app/resto:/app/resto:ro
      - ./app/vendor:/app/vendor:ro
  restodb:
    environment:
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_SHARED_BUFFERS=1GB
      - POSTGRES_WORK_MEM=32MB
      - POSTGRES_MAINTENANCE_WORK_MEM=320MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=3GB
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    volumes:
      - ./tmp:/backup