version: '3'
volumes:
  database_data:
    driver: local
  static_content:
    driver: local
networks:
  default:
    driver: bridge
  external:
    external:
      name: rnet 
services:
  restodb:
    image: jjrom/resto-database:6.0
    restart: always
    build:
      context: ./
      dockerfile: ./build/resto-database/Dockerfile
    # Upgrade shared_memory for complex queries
    # shm_size: '2gb'
    command: docker-entrypoint.sh -c config_file=/etc/postgresql.conf
    networks:
      - default
      - external
    env_file:
      - ${ENV_FILE:-config.env}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD:-resto}
      - POSTGRES_USER=${DATABASE_USER_NAME:-resto}
      - POSTGRES_DB=${DATABASE_NAME:-resto}
      - POSTGRES_HOST=${DATABASE_HOST:-localhost}
      - POSTGRES_PORT=${DATABASE_PORT:-5432}
    ports:
      - ${DATABASE_EXPOSED_PORT:-5253}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER_NAME:-resto}"]
      interval: 1m
      timeout: 5s
    volumes:
      - ${POSTGRES_DATA:-database_data}:/var/lib/postgresql/data
