version: '3'
services:
  resto:
    environment: 
      # Set to 0 in production environment to activate opcache
      - RESTO_DEBUG=1
      - PHP_ENABLE_XDEBUG=1
      - NGINX_CLIENT_MAX_BODY_SIZE=20m
      - ADDON_GAZETTEER_EGG_ENDPOINT=https://egg.snapplanet.io
    volumes:
      - ./app/resto/core:/app/resto/core:ro
      - ./app/vendor:/app/vendor:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/src/STAC.php:/app/resto/addons/STAC.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/src/STACCatalog.php:/app/resto/addons/STACCatalog.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/stac.config:/cfg/stac.config:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-view/view.config:/cfg/view.config:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-view/src/View.php:/app/resto/addons/View.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-gazetteer/gazetteer.config:/cfg/gazetteer.config:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-gazetteer/src/Gazetteer.php:/app/resto/addons/Gazetteer.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-hashtag/src/Hashtag.php:/app/resto/addons/Hashtag.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-hashtag/hashtag.config:/cfg/hashtag.config:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-mvt/mvt.config:/cfg/mvt.config:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-mvt/src/MVT.php:/app/resto/addons/MVT.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-heatmap/heatmap.config:/cfg/heatmap.config:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-heatmap/src/Heatmap.php:/app/resto/addons/Heatmap.php:ro
      - /Users/jrom/Devel/resto-models/src/S2PEPSModel.php:/app/resto/addons/S2PEPSModel.php:ro
      - /Users/jrom/Devel/resto-models/src/S1PEPSModel.php:/app/resto/addons/S1PEPSModel.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-shp-uploader/src/php-shapefile/:/app/resto/addons/php-shapefile:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-shp-uploader/src/ShapefileUploader.php:/app/resto/addons/ShapefileUploader.php:ro
      - /Users/jrom/Devel/resto-addons/resto-addon-shp-uploader/shp-uploader.config:/cfg/shp-uploader.config:ro
      - /Users/jrom/Devel/resto-models/src/HysopeLakeModel.php:/app/resto/addons/HysopeLakeModel.php:ro
  restodb:
    environment:
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_SHARED_BUFFERS=1GB
      - POSTGRES_WORK_MEM=32MB
      - POSTGRES_MAINTENANCE_WORK_MEM=320MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=3GB
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    volumes:
      - ./tmp:/backup