version: '3'
services:
  resto:
    environment: 
      # Set to 0 in production environment to activate opcache
      - RESTO_DEBUG=1
      - PHP_ENABLE_XDEBUG=1
      - NGINX_CLIENT_MAX_BODY_SIZE=20m
    volumes:
      - ./app:/app
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/src/STAC.php:/app/resto/addons/STAC.php
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/src/STACCatalog.php:/app/resto/addons/STACCatalog.php
      - /Users/jrom/Devel/resto-addons/resto-addon-stac/stac.config:/cfg/stac.config
      - /Users/jrom/Devel/resto-addons/resto-addon-view/view.config:/cfg/view.config
      - /Users/jrom/Devel/resto-addons/resto-addon-view/src/View.php:/app/resto/addons/View.php
      - /Users/jrom/Devel/resto-addons/resto-addon-mvt/mvt.config:/cfg/mvt.config
      - /Users/jrom/Devel/resto-addons/resto-addon-mvt/src/MVT.php:/app/resto/addons/MVT.php
      - /Users/jrom/Devel/resto-addons/resto-addon-heatmap/heatmap.config:/cfg/heatmap.config
      - /Users/jrom/Devel/resto-addons/resto-addon-heatmap/src/Heatmap.php:/app/resto/addons/Heatmap.php
      - /Users/jrom/Devel/resto-models/src/S2PEPSModel.php:/app/resto/addons/S2PEPSModel.php
  restodb:
    environment:
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_SHARED_BUFFERS=1GB
      - POSTGRES_WORK_MEM=32MB
      - POSTGRES_MAINTENANCE_WORK_MEM=320MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=3GB
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    volumes:
      - ./tmp:/backup